### ISSUE TITLE
cd leak

### ISSUE THREAD

**Issue by lohhiiccc** [lohhiiccc/Minishell#69]
```
➜  Minishell git:(fix_leak) valgrind --suppressions=supress.txt  --show-leak-kinds=all --leak-check=full --trace-children=yes --track-fds=yes ./minishell 
==32940== Memcheck, a memory error detector
==32940== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==32940== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==32940== Command: ./minishell
==32940== 
[🥚][/home/lrio/Documents/Minishell] Minichel$ cd ..
[🥚][/home/lrio/Documents] Minichel$ 
Exit
==32940== 
==32940== FILE DESCRIPTORS: 3 open (3 std) at exit.
==32940== 
==32940== HEAP SUMMARY:
==32940==     in use at exit: 208,413 bytes in 227 blocks
==32940==   total heap usage: 592 allocs, 365 frees, 252,781 bytes allocated
==32940== 
==32940== 21 bytes in 1 blocks are definitely lost in loss record 11 of 68
==32940==    at 0x484DCD3: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==32940==    by 0x49DB7BC: getcwd (getcwd.c:86)
==32940==    by 0x4066EF: change_env (cd.c:109)
==32940==    by 0x406586: ft_cd (cd.c:50)
==32940==    by 0x402D06: exec_build_in (exec_build_in.c:25)
==32940==    by 0x401C90: exec_cmd (exec_cmd.c:36)
==32940==    by 0x401B38: exec_args (exec.c:31)
==32940==    by 0x4044C4: create_and_exec_tree (prompt.c:75)
==32940==    by 0x40431C: prompt (prompt.c:52)
==32940==    by 0x4013C8: main (main.c:37)
==32940== 
==32940== 31 bytes in 1 blocks are definitely lost in loss record 15 of 68
==32940==    at 0x484DCD3: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==32940==    by 0x49DB7BC: getcwd (getcwd.c:86)
==32940==    by 0x4064BC: ft_cd (cd.c:35)
==32940==    by 0x402D06: exec_build_in (exec_build_in.c:25)
==32940==    by 0x401C90: exec_cmd (exec_cmd.c:36)
==32940==    by 0x401B38: exec_args (exec.c:31)
==32940==    by 0x4044C4: create_and_exec_tree (prompt.c:75)
==32940==    by 0x40431C: prompt (prompt.c:52)
==32940==    by 0x4013C8: main (main.c:37)
==32940== 
==32940== LEAK SUMMARY:
==32940==    definitely lost: 52 bytes in 2 blocks
==32940==    indirectly lost: 0 bytes in 0 blocks
==32940==      possibly lost: 0 bytes in 0 blocks
==32940==    still reachable: 0 bytes in 0 blocks
==32940==         suppressed: 208,361 bytes in 225 blocks
==32940== 
==32940== For lists of detected and suppressed errors, rerun with: -s
==32940== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)

```

**Comment by lohhiiccc** [comment]
```
➜  Minishell git:(76-leaks-in-heredoc) ./minishell 
[🥚][/home/lrio/Documents/Minishell] Minichel$ cd ..
[🥚][/home/lrio/Documents] Minichel$ 
Exit

=================================================================
==131782==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x49a569 in realloc (/home/lrio/Documents/Minishell/minishell+0x49a569)
    #1 0x7fe6929997bc in getcwd io/../sysdeps/unix/sysv/linux/getcwd.c:86:8
    #2 0x4d9b41 in ft_cd /home/lrio/Documents/Minishell/srcs/build-in/cd.c:35:12
    #3 0x4d043b in exec_build_in /home/lrio/Documents/Minishell/srcs/exec/exec_build_in.c:25:9
    #4 0x4cd14f in exec_cmd /home/lrio/Documents/Minishell/srcs/exec/exec_cmd.c:36:9
    #5 0x4ccbf3 in exec_args /home/lrio/Documents/Minishell/srcs/exec/exec.c:31:8
    #6 0x4d4bd8 in create_and_exec_tree /home/lrio/Documents/Minishell/srcs/prompt/prompt.c:73:15
    #7 0x4d47ef in prompt /home/lrio/Documents/Minishell/srcs/prompt/prompt.c:50:11
    #8 0x4cb54e in main /home/lrio/Documents/Minishell/srcs/main.c:37:9
    #9 0x7fe6928add8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

Direct leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x49a569 in realloc (/home/lrio/Documents/Minishell/minishell+0x49a569)
    #1 0x7fe6929997bc in getcwd io/../sysdeps/unix/sysv/linux/getcwd.c:86:8
    #2 0x4da057 in change_env /home/lrio/Documents/Minishell/srcs/build-in/cd.c:109:32
    #3 0x4d9ca7 in ft_cd /home/lrio/Documents/Minishell/srcs/build-in/cd.c:50:2
    #4 0x4d043b in exec_build_in /home/lrio/Documents/Minishell/srcs/exec/exec_build_in.c:25:9
    #5 0x4cd14f in exec_cmd /home/lrio/Documents/Minishell/srcs/exec/exec_cmd.c:36:9
    #6 0x4ccbf3 in exec_args /home/lrio/Documents/Minishell/srcs/exec/exec.c:31:8
    #7 0x4d4bd8 in create_and_exec_tree /home/lrio/Documents/Minishell/srcs/prompt/prompt.c:73:15
    #8 0x4d47ef in prompt /home/lrio/Documents/Minishell/srcs/prompt/prompt.c:50:11
    #9 0x4cb54e in main /home/lrio/Documents/Minishell/srcs/main.c:37:9
    #10 0x7fe6928add8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: 52 byte(s) leaked in 2 allocation(s).

```

**Comment by lohhiiccc** [comment]
mb wrong branch
